tinymce.addI18n('pt_BR',{
  "Redo": "Refazer",
  "Undo": "Desfazer",
  "Cut": "Recortar",
  "Copy": "Copiar",
  "Paste": "Colar",
  "Select all": "Selecionar tudo",
  "New document": "Novo documento",
  "Ok": "Ok",
  "Cancel": "Cancelar",
  "Visual aids": "Ajuda visual",
  "Bold": "Negrito",
  "Italic": "Itálico",
  "Underline": "Sublinhado",
  "Strikethrough": "Tachado",
  "Superscript": "Sobrescrito",
  "Subscript": "Subscrito",
  "Clear formatting": "Limpar formatação",
  "Align left": "Alinhar à esquerda",
  "Align center": "Alinhar ao centro",
  "Align right": "Alinhar à direita",
  "Align justify": "Justificar",
  "Bullet list": "Lista com marcadores",
  "Numbered list": "Lista numerada",
  "Decrease indent": "Diminuir recuo",
  "Increase indent": "Aumentar recuo",
  "Close": "Fechar",
  "Formats": "Formatos",
  "Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.": "Seu navegador não suporta acesso direto à área de transferência. Por favor utilize os atalhos Ctrl+X/C/V.",
  "Headers": "Cabeçalhos",
  "Heading 1": "Título 1",
  "Heading 2": "Título 2",
  "Heading 3": "Título 3",
  "Heading 4": "Título 4",
  "Heading 5": "Título 5",
  "Heading 6": "Título 6",
  "Paragraph": "Parágrafo",
  "Blockquote": "Citação",
  "Inline": "Em linha",
  "Blocks": "Blocos",
  "Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.": "Colar agora está no modo texto simples. Conteúdos serão colados como texto simples até você desligar essa opção.",
  "Fonts": "Fontes",
  "Font sizes": "Tamanhos de fonte",
  "Class": "Classe",
  "Browse": "Procurar",
  "Icons": "Ícones",
  "More...": "Mais...",
  "Select...": "Selecionar...",
  "Insert": "Inserir",
  "File": "Arquivo",
  "Edit": "Editar",
  "View": "Visualizar",
  "Format": "Formatar",
  "Table": "Tabela",
  "Tools": "Ferramentas",
  "Help": "Ajuda",
  "Fullscreen": "Tela cheia",
  "Source code": "Código fonte",
  "Insert/edit image": "Inserir/editar imagem",
  "Insert link": "Inserir link",
  "Remove link": "Remover link",
  "Preview": "Pré-visualizar",
  "Print": "Imprimir",
  "Insert/edit media": "Inserir/editar mídia",
  "Alternative description": "Descrição alternativa",
  "Dimensions": "Dimensões",
  "Advanced": "Avançado"
});
